<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>dubbo-plus</artifactId>
        <groupId>net.dubboclub</groupId>
        <version>0.0.6</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <version>0.0.8</version>
    <groupId>net.dubboclub</groupId>
    <artifactId>cat-monitor</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java_source_version>1.8</java_source_version>
        <java_target_version>1.8</java_target_version>
        <slf4j.version>1.7.25</slf4j.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>
            <version>3.0.6</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <distributionManagement>
        <repository>
            <id>releases</id>
            <name>Nexus Release Repository</name>
            <url>http://maven.jindidata.com/nexus/content/repositories/releases</url>
        </repository>
        <snapshotRepository>
            <id>snapshots</id>
            <name>Nexus Snapshot Repository</name>
            <url>http://maven.jindidata.com/nexus/content/repositories/snapshots</url>
        </snapshotRepository>
    </distributionManagement>

</project>
