project.name=cat
sentinel.server=172.28.86.222:9090
sentinel.nacos.remoteAddress=172.27.209.204:8848,172.27.209.205:8848,172.27.209.206:8848
sentinel.nacos.groupId=cat
sentinel.nacos.dataId=cat-flow-rules
sentinel.nacos.namespace=sentinel
