project.name=cat
sentinel.server=172.27.207.254:9090
sentinel.nacos.remoteAddress=172.28.82.66:8848,172.28.82.67:8848,172.28.82.68:8848
sentinel.nacos.groupId=cat
sentinel.nacos.dataId=cat-flow-rules
sentinel.nacos.namespace=sentinel
